# Epic: observability_master
# Lifecycle: permanent
"""``health_consolidator`` per-consolidator catalog loading — split out of the facade (2026-07-31).

The catalog is a PROJECTION of the deployment-service terraform consolidator locals,
generated by ``scripts/gen_consolidator_catalog.py`` and committed as a JSON artifact so it
travels with the deployed image (deployment-service is NOT on the Cloud Run image). Adding a
consolidator = a terraform edit + a generator re-run; the facade endpoint then shows it
automatically.

No module-level collaborator here is a test-patched seam (``resolve_deployment_env_short`` /
``UnifiedCloudConfig`` are exercised for real, never mocked by name) — safe as its own module.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from unified_trading_library import UnifiedCloudConfig
from unified_trading_library.cloud_interface.bucket_naming import (  # noqa: qg-deep-import
    _resolve_deployment_env_short,  # not re-exported from the UTL top-level package
)

logger = logging.getLogger(__name__)

_CATALOG_PATH = Path(__file__).resolve().parent.parent.parent / "consolidator_catalog.generated.json"


def _load_catalog() -> list[dict[str, str | None]]:
    try:
        doc = json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        logger.warning("consolidator-health: catalog load failed (%s) — estate view empty", exc)
        return []
    entries = doc.get("consolidators")
    return list(entries) if isinstance(entries, list) else []


_CATALOG: list[dict[str, str | None]] = _load_catalog()

_env_project_cache: tuple[str, str] | None = None


def _env_project() -> tuple[str, str]:
    """(deployment_env_short, gcp_project_id) — the two slots a catalog ``bucket_template`` fills. Cached."""
    global _env_project_cache
    if _env_project_cache is None:
        _env_project_cache = (_resolve_deployment_env_short(), UnifiedCloudConfig().gcp_project_id)
    return _env_project_cache


def _catalog_bucket(entry: dict[str, str | None]) -> str:
    """Fill a catalog ``bucket_template`` (``…-{env}-{project}``) with the live env/project."""
    env, project = _env_project()
    return (entry["bucket_template"] or "").format(env=env, project=project)
